// Dynamic aggregator for all 3D entity components in this folder and subfolders
// Uses Vite's import.meta.glob with eager option to collect modules at build time
// This allows us to automatically export all components without manually listing them
// Each component file should export a React component, preferably with a name ending in "3D" for clarity
// Example usage: import { Entities } from './entities'; then use <Entities.Alicates3D /> or <Entities['herramientas/Alicates3D'] />
// Note: This file should be placed in the 'entities' folder, and it will automatically include all .jsx files in that folder and its subfolders
// For more control, you can still export specific components manually if needed, but this dynamic approach reduces boilerplate and maintenance
// Example of a component file (e.g. Alicates3D.jsx):
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alicates3D.glb
*/
import AlicatesPICOhd from './herramientas/AlicatesPICOhd';

const modules = import.meta.glob('./**/*.jsx', { eager: true });

const Entities = {};

function pickExport(mod) {
  if (mod.default) return mod.default;
  // Prefer any named export that ends with 3D
  const named = Object.keys(mod).find(k => /3D$/.test(k));
  if (named) return mod[named];
  // Fallback: return the module object itself
  return mod;
}

for (const path in modules) {
  const mod = modules[path];
  // path like './Armario3D.jsx' or './herramientas/Alicates3D.jsx'
  const filePath = path.replace('./', '').replace(/\.jsx?$/, '');
  const baseName = filePath.split('/').pop();
  const comp = pickExport(mod);

  // expose by relative path key
  Entities[filePath] = comp;
  // also expose by base filename (e.g. Alicates3D) for convenience
  if (!Entities[baseName]) Entities[baseName] = comp;
}

export default Entities;
export { Entities };
