/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alicatesPICOhd.glb 
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alicatesPICOhd.glb 
*/

// src/components/3d/entities/herramientas/AlicatesPicoCurvo3D.jsx
import React, { useState } from 'react';
import { Box, Cylinder, Edges } from '@react-three/drei';
import { COLORS } from '../../core/config';

export const AlicatesPicoCurvo3D = ({
  position,
  rotation = [0, 0, 0],
  onClick,
  isSelected = false,
  yOffset = 0,
}) => {
  const [hovered, setHovered] = useState(false);
  const color = isSelected ? COLORS.selected : (hovered ? '#ccaa88' : '#aa8866');
  const metalDark = '#8B6914';
  const metalLight = '#C5A059';

  // La parte más baja de los mangos está en y ≈ -0.15
  const BASE_Y_OFFSET = 0.15;

  return (
    <group
      position={[position.x, position.y + yOffset + BASE_Y_OFFSET, position.z]}
      rotation={rotation}
      onClick={(e) => { e.stopPropagation(); onClick?.(); }}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      {/* ========== MANGO IZQUIERDO (barra larga) ========== */}
      <Box args={[0.24, 0.05, 0.08]} position={[-0.12, -0.08, 0]} rotation={[0, 0, 0.35]}>
        <meshStandardMaterial color={color} metalness={0.7} roughness={0.4} />
        <Edges color="#ffffff" threshold={15} lineWidth={0.5} />
      </Box>

      {/* ========== MANGO DERECHO ========== */}
      <Box args={[0.24, 0.05, 0.08]} position={[0.12, -0.08, 0]} rotation={[0, 0, -0.35]}>
        <meshStandardMaterial color={color} metalness={0.7} roughness={0.4} />
        <Edges color="#ffffff" threshold={15} lineWidth={0.5} />
      </Box>

      {/* ========== EJE CENTRAL (tornillo cilíndrico) ========== */}
      <Cylinder args={[0.045, 0.045, 0.1, 12]} position={[0, 0.02, 0]} rotation={[0, 0, 0]}>
        <meshStandardMaterial color="#888888" metalness={0.8} roughness={0.2} />
      </Cylinder>
      <Cylinder args={[0.065, 0.065, 0.02, 8]} position={[0, 0.07, 0]}>
        <meshStandardMaterial color="#aaaaaa" metalness={0.9} />
      </Cylinder>
      <Cylinder args={[0.065, 0.065, 0.02, 8]} position={[0, -0.03, 0]}>
        <meshStandardMaterial color="#aaaaaa" metalness={0.9} />
      </Cylinder>

      {/* ========== MORDAZA IZQUIERDA (triángulo alargado) ========== */}
      <group>
        {/* Base de la mordaza (prisma rectangular que se conecta al eje) */}
        <Box args={[0.14, 0.04, 0.1]} position={[-0.08, 0.07, 0]} rotation={[0, 0, 0.5]}>
          <meshStandardMaterial color={metalDark} metalness={0.8} roughness={0.3} />
        </Box>
        {/* Segmento intermedio (estrechamiento) */}
        <Box args={[0.08, 0.03, 0.08]} position={[-0.15, 0.13, 0]} rotation={[0, 0, 0.65]}>
          <meshStandardMaterial color={metalLight} metalness={0.8} />
        </Box>
        {/* Punta curva (pico de loro) - girada hacia abajo y derecha */}
        <Box args={[0.07, 0.025, 0.06]} position={[-0.19, 0.18, 0.04]} rotation={[0.6, 0.2, 0.8]}>
          <meshStandardMaterial color={metalLight} metalness={0.85} />
        </Box>
      </group>

      {/* ========== MORDAZA DERECHA ========== */}
      <group>
        <Box args={[0.14, 0.04, 0.1]} position={[0.08, 0.07, 0]} rotation={[0, 0, -0.5]}>
          <meshStandardMaterial color={metalDark} metalness={0.8} roughness={0.3} />
        </Box>
        <Box args={[0.08, 0.03, 0.08]} position={[0.15, 0.13, 0]} rotation={[0, 0, -0.65]}>
          <meshStandardMaterial color={metalLight} metalness={0.8} />
        </Box>
        {/* Punta curva simétrica */}
        <Box args={[0.07, 0.025, 0.06]} position={[0.19, 0.18, 0.04]} rotation={[-0.6, -0.2, -0.8]}>
          <meshStandardMaterial color={metalLight} metalness={0.85} />
        </Box>
      </group>
    </group>
  );
};

export default AlicatesPicoCurvo3D;